### ISSUE TITLE
Run a rule on a glob

### ISSUE THREAD

**Issue by AugustinLF** [eps1lon/eslint-focus#23]
When using a glob instead of a path, the glob gets unfurled but `eslint-focus` errors:

```
npx eslint-focus @klapp-tooling/fixtures-assets/no-cdn-assets ./packages/features/pf-*

Unknown arguments: ./packages/features/pf-categories, ./packages/features/pf-connect, ./packages/features/pf-financial-stories, ./packages/features/pf-monthly-cycle, ./packages/features/pf-notification-settings, ./packages/features/pf-playground, ./packages/features/pf-spending-breakdown
```

Not a necessity, but it would be nice :) I'd be happy to contribute if that's something you'd prefer :)

**Comment by eps1lon** [comment]
Yeah support for multiple paths makes sense. That way you could also manually enumerate e.g. `$0 <rule> ./packages/traits ./packages/test`
